---
title: "Kattegat_Case_Study_Chronic_Trawling"
output: html_document
date: "2024-07-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(naniar)
library(SRS)
library(ggfortify)
library(broom)
library(RColorBrewer)
library(ggpubr)
library(ade4)
library(nlme)
library(gplots)
library(scales)
library(adespatial)
library(phyloseq)
library(ggiraphExtra)
library(MicrobeR)
library(ANCOMBC)
```
#Meiofauna
#18S data
```{r data input}
meta <- read.csv("18S_meta_Kattegat.csv", header=T)%>%
  dplyr::rename(ID=sampleID_for_now)
meta$User.ID <- gsub(".1b", "", meta$User.ID)  
meta$User.ID <- gsub(".2b", "", meta$User.ID) 

counts <- read.table("silva132/ASV_table.tsv", stringsAsFactors = F, header =T)%>%
          gather(sample,count, 2:ncol(.))%>%
          filter(count > 0)%>%
          dplyr::rename(ID = sample)

taxa <- read.delim("silva132/ASV_tax.silva_132.tsv",stringsAsFactors = FALSE, header=TRUE)%>%
 filter(Kingdom %in% "Eukaryota")%>%
        replace_with_na_if(.predicate = is.character,
                          condition = ~.x %in% (""))%>%
        replace_na(list(Kingdom="zz_Unclassified"))%>%
        replace_na(list(Phylum="zz_Unclassified"))%>%
        replace_na(list(Class="zz_Unclassified"))%>%
        replace_na(list(Order="zz_Unclassified"))%>%
        replace_na(list(Family="zz_Unclassified"))%>%
        replace_na(list(Genus="zz_Unclassified"))%>%
        replace_na(list(Species="zz_Unclassified"))

wide_relab_cat <- Tab_two %>%  
  dplyr::select(ASV_ID,ID, relab) %>% 
  spread(ASV_ID,relab, fill= 0) %>% 
  remove_rownames() %>%
  column_to_rownames(var = "ID")

Tab_all_n <- counts%>% 
  left_join(meta, by="ID") %>% 
  left_join(taxa, by="ASV_ID")%>%
  filter(Kingdom %in% "Eukaryota")

Tab_all <- Tab_all_n %>%
   filter(!Phylum %in% c( "Hemichordata", "Echinodermata", "Ctenophora","Cercozoa","Ciliophora","Retaria"))%>%
  filter(Phylum %in% c("Annelida","Arthropoda","Brachiopoda","Bryozoa","Cnidaria","Gastrotricha", "Kinorhyncha", "Mollusca", "Nematoda", "Nemertea", "Opisthokonta_ph", "Platyhelminthes", "Porifera", "Priapulida","Rotifera", "Tunicata", "Xenacoelomorpha"  ))%>%
  group_by(User.ID) %>% 
  filter(sum(count) >= 1000) %>% 
  mutate(relab = count/sum(count)) %>%
  ungroup()

```

```{r define colors}
cols.trawl <- c(
  "trawled" = "maroon",
  "control" = "yellowgreen"
)

cols.class<- c(
"Nematoda"="#84afde",
"Echinodermata" = "#fb9a99",
"Kinorhyncha"="#9eb383",
"Arthropoda" ="#1f78b4",
"Cnidaria" ="#d49abe",
"Gastrotricha"="lightgoldenrod" ,
"Mollusca" ="#7ab5bc",
"Nemertea" = "#ddcaff",
"Gnathostomulida"= "#73cfc6",
"Priapulida" ="#ffffcd", 
"Brachiopoda" ="#f8cea0",
"Ostracoda" ="violet"  )

cols.site <- c(
 "CL1" ="#95004b",
 "CL2" = "#c50046",
  "CL3" ="#ff9a94",
"CL4"  ="#500200",
"CL5"  ="#291200",
"CL8"  = "#8e4100",
"Anholt" = "#ffc197",
"N10" = "#ffa93b",
"N12" = "#fff1d0",
"PP1" ="#b99d00",
"PP2" ="#f6ff70",
"PP3" ="#adc000",
"PP4" ="#6bf63c",
"PP5" ="#0d4f00",
"PP6" ="#00bb50",
"PP7" ="#009762",
"PP10" ="#002d1d",
"PP11" ="#7dffcf",
"R3" ="#01f4f9",
"R5" ="#c8f6ff",
"SP3" ="#86d0ff",
"SP4" ="#0155a7",
"SP5" ="#283ae1",
"SP6" ="#f1cbff",
"SP7" ="#ff77ce",
"SP8" ="#ffc3d5"
)

cols.SAR <- c(
  "0"="grey7",
  "1.597"="#d2522c",
  "2.522"="#de946d",
  "2.768"="#9d5e2f",
  "4.209"="#d69332",
  "4.301"="#ada85c",
  "4.592"="#b3b736",
  "4.633"="#6a7227",
  "5.181"="#63b445",
  "5.24"="#3a814d",
  "5.675"="#5fbe84",
  "5.76"="#3fbfbc",
  "6.238"="#4f9ed5",
  "6.273"="#5d5fa5",
  "7.164"="#5e6bdb",
  "7.259"="#9a92dd",
  "8.595"="#a25bc7",
  "10.833"="#cc53b2",
  "12.478"="#db88b2",
  "13.483"="#9d4b6c",
  "14.375"="#d84380"
  )

cols.SAR_group <- c(
  "0" ="#e1c2aa",
"<3"="#bed8b5",
"<6" ="#a2d5d6",
"<9" ="#afc2e3",
"<15" ="#debbd4"
)

```

```{r rarefaction curve}
#rarefy
countsRAW <- Tab_all_n  %>% 
  dplyr::select(ASV_ID, ID, count) %>% 
  spread(ASV_ID,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "ID")

(raremax <- min(rowSums(countsRAW))) #98265

#Rarefaction curve plot
out<- rarecurve(countsRAW, step = 20, sample = raremax, cex = 0.6, label = F)
Nmax <- sapply(out, function(x) max(attr(x, "Subsample")))
Smax <- sapply(out, max)
 
 
col <- c("black", "black")
set.seed(3)
grp <- factor(sample(seq_along(col), nrow(countsRAW), replace = TRUE))
cols <- col[grp] 
 
 
 plot(c(1, max(Nmax)), c(1, max(Smax)), xlab = "Sample Size",
     ylab = "Species", type = "n")
abline(v = raremax)
for (i in seq_along(out)) {
    N <- attr(out[[i]], "Subsample")
    lines(N, out[[i]], col = cols[i])
}
```

```{r alpha diversity}
#SRS analysis
example_input_data <- Tab_all %>%
  group_by(ASV_ID, User.ID)%>%
 summarise(count=sum(count))%>%
   ungroup()%>%
  dplyr::select(ASV_ID, User.ID, count)%>%
  spread(User.ID,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "ASV_ID")

Cmin <- min(colSums(example_input_data))
Cmin

SRS_output <- SRS(data = example_input_data, Cmin = Cmin)

#Shannon Diversity Index
SRSshannon<- SRS_output %>%
  t()%>%
  data.frame()%>% 
  rownames_to_column(var="User.ID")%>% 
  plyr::ddply(~User.ID, function(x) {vegan::diversity(x[-1], index="shannon")}) %>%
  dplyr::rename(shannon= V1) %>% #Shannon 
  left_join(Tab_all, by="User.ID")



SRSshannon$SAR_type<- factor(SRSshannon$SAR_type,levels=c("MPA",
                    "low" ,
                   "medium",
                    "high",
                   "very high"))

shan.lm <- lm(shannon ~ SAR_2014_10, SRSshannon)

alpha_site_shan <-SRSshannon %>%
 ggplot(aes(x = SAR_2014_10, y = shannon, color=SAR_type, group=as.character(SAR_2014_10))) +
   geom_point(size=7) +
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
 labs(x = "SAR 2014", y = "Shannon´s H", size=6) +
   scale_color_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))+
   theme_classic()+  theme(
    legend.position = 'right',
    axis.text.x=element_text(angle = -45, hjust = 0)
  )+
    geom_vline(xintercept = 1.0,linetype = "solid")+
   geom_abline(slope = coef(shan.lm)[["SAR_2014_10"]], 
              intercept = coef(shan.lm)[["(Intercept)"]],
              linetype= "dashed", color="grey76")+
   guides(colour = guide_legend(override.aes = list(size=6), title="SAR 2014", nrow=13))+
   scale_x_continuous(breaks = scales::pretty_breaks(n = 7))+
 
  labs(title = paste("Adj R2 = ",signif(summary(shan.lm)$adj.r.squared, 5),
"Intercept =",signif(shan.lm$coef[[1]],5 ),
" Slope =",signif(shan.lm$coef[[2]], 5),
" P =",signif(summary(shan.lm)$coef[2,4],5)), size=6)


#Stats
#Shannon
SRSshannon_av <- SRSshannon%>%
  group_by(ID, SAR_2014_10,  site)%>%
  summarise(shannon = mean(shannon))%>%
  ungroup()

test2 <-lme(shannon ~ 1 + SAR_2014_10, data=SRSshannon_av, random=~1|site, method="REML") 
aov2 <-anova(test2)
aov2
```

```{r db-RDA beta diversity}
wide_dbrda <-Tab_all%>%
  dplyr::select(ASV_ID, User.ID, relab)%>%
  group_by(ASV_ID, User.ID)%>%
    filter(row_number() ==1)%>%
  ungroup()%>%
  dplyr::select(ASV_ID, User.ID, relab) %>% 
  spread(ASV_ID,relab, fill= 0) %>% 
  remove_rownames() %>%
  column_to_rownames(var = "User.ID")

#dissimilarity matrix based on Bray Curtis
BC.dist=vegdist(wide_dbrda, distance="bray")


meta_kat_sum <- meta%>%
  dplyr::select(User.ID, water_depth, OM_pct , porosity ,DBD , chl , BPc_WW_10 , IPc_WW_10 ,  
                totWW_10 ,BQI_2009_10 , D_10 , SAR_2014_10 , swm_d_10 ,  log_swm_d_plus_1_10,salt_range_cmems_10,
                o2_range_cmems_10,curr_median_cmems_10,o2_min_cmems_10, PRT.CHO_ratio_0.2cm,curr_range_cmems_10, SAR_group, MI) %>%
  group_by(User.ID)%>%
  mutate(OM_pct = mean(OM_pct))%>%
  mutate(porosity =mean(porosity))%>%
  mutate(DBD =mean(DBD))%>%
  mutate(chl = mean(chl))%>%
  filter(row_number() ==1)%>%
  ungroup() 


meta_kat_sum$SAR_group <- as.factor(meta_kat_sum$SAR_group)

#use capscale to make a db-RDA
dbRDA=capscale(BC.dist ~
            o2_min_cmems_10+
            PRT.CHO_ratio_0.2cm,
                  data=meta_kat_sum , dist="bray")

#check for collinearity of your env.var.
vif<- vif.cca(dbRDA)
vif 

#Anova with permutation within bays

set.seed(10)
anova(dbRDA, by = "margin",model="direct", permutations = 9999)
##Calculate the eigenvalues for the first and second dimension
dpRDA.eigs    <- dbRDA$CCA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))
dpRDA.eigs.uncon    <- dbRDA$CA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))

#Overview how much will be epxlained by the axis
expl_var <- c(dpRDA.eigs , dpRDA.eigs.uncon) 

#Plot
scrs <- vegan::scores(dbRDA, display=c("sp","wa","lc","bp","cn"))
df_sites<-data.frame(scrs$sites,t(as.data.frame(rownames(scrs$sites))))%>%
  dplyr::select(CAP1, CAP2)%>%
  rownames_to_column(var="User.ID")
df_sites <-df_sites

df_sites <- df_sites %>% 
  inner_join(
meta_kat_sum, by="User.ID")

df_sites$SAR_type<- factor(df_sites$SAR_type,levels=c("MPA",
                    "low" ,
                   "medium",
                    "high",
                   "very high"))
#Draw sites
p<-ggplot()
p<-p+geom_point(data=df_sites,aes(CAP1,CAP2,colour=SAR_type, size=7))+
  #scale_color_manual(values=cols.trawl)
  scale_color_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))
# scale_color_stepsn(n.breaks = 8, colours = rev(viridis::viridis(10)))
#Draw biplots
multiplier <- vegan:::ordiArrowMul(scrs$biplot*1)

df_arrows<- scrs$biplot*multiplier
colnames(df_arrows)<-c("CAP1","CAP2")
df_arrows=as.data.frame(df_arrows)

p<-p+geom_segment(data=as.data.frame(df_arrows), aes(x = 0, y = 0, xend = CAP1, yend = CAP2),
                 arrow = arrow(length = unit(0.2, "cm")))

p<-p+geom_text(data=as.data.frame(df_arrows*1),aes(CAP1, CAP2, label = rownames(df_arrows)))+
  theme_classic()+
  theme(legend.position = "right")+
   guides(colour = guide_legend(override.aes = list(size=7), title="SAR 2014", nrow=13))
p



```

```{r bubble plot}
Tab_all$SAR_type<- factor(Tab_all$SAR_type,levels=c("MPA",
                    "low" ,
                   "medium",
                    "high",
                   "very high"))


meio_over <-Tab_all %>%
    group_by(SAR_type, Order)%>%
  filter(relab>0.01)%>%
  ungroup() %>%
  group_by(SAR_type, Order)%>%
  mutate(relab=mean(relab))%>%
  ungroup()
  
meio_under2 <-Tab_all %>%
    group_by(SAR_type, Order)%>%
  filter(!relab>0.01) %>%
  mutate(Order = "Other")

meioa_all <-rbind(meio_over, meio_under2)
  
  meioa_all %>%
      mutate(Order = reorder(Order, -relab, sum)) %>% 

  ggplot(aes(x=SAR_type, y=Order, size=relab, fill=Order)) +
    geom_point(alpha=0.5, shape=21, color="black") +
    scale_size(range = c(.1, 15), name="Relative abundance >1 %") +
    scale_fill_viridis(discrete=TRUE, guide=FALSE, option="A") +
    theme_ipsum() +
    theme(legend.position="right") +
    ylab("Order") +
      xlab("SAR 2014")

```

```{r combine figures}
two <-ggarrange(alpha_site_shan, p, labels=c("A","B"))
ggarrange(two, all, nrow=2,labels = c("","C"))
```

```{r differential abundance analysis }

filter <- Tab_all %>%
    group_by(SAR_type, Order)%>%
  filter(relab>0.01)%>%
  ungroup() %>%
  group_by(SAR_type,Order)%>%
  mutate(relab=mean(relab))%>%
  ungroup()%>% dplyr::select(Order)%>%
  unique()

df <- Tab_all %>% 
    right_join(filter, by="Order")%>%
   group_by(ASV_ID, User.ID)%>%
 summarise(count=sum(count))%>%
   ungroup()
  
  spread(User.ID,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "ASV_ID")

meta_da<- meta %>%
  filter(project %in% "kattegat")%>%
  dplyr::select(User.ID, SAR_type, site)%>%
  group_by(User.ID)%>%
  filter(row_number() ==1)%>%
  ungroup()%>%
  remove_rownames()%>%
  column_to_rownames(var="User.ID")
meta_da$SAR_type<- as.character(meta_da$SAR_type)

OTU=otu_table(df, taxa_are_rows = TRUE)
META = sample_data(meta_da)
TAXA <- taxa %>% 
  dplyr::select("ASV_ID","Kingdom","Phylum","Class","Order","Family","Genus")%>% 
  remove_rownames()%>%
  column_to_rownames(var="ASV_ID")
TAXA = as.matrix(TAXA)
TAXA=tax_table(TAXA)
phyl_obj <- phyloseq(OTU, META, TAXA)

sample_data(phyl_obj)$SAR_type <- as.factor(sample_data(phyl_obj)$SAR_type)
sample_data(phyl_obj)$SAR_type<- relevel(sample_data(phyl_obj)$SAR_type, "MPA")

output = ancombc2(data = phyl_obj, assay_name = "counts", tax_level = "Order",
                  fix_formula = "SAR_type", rand_formula = NULL,
                  p_adj_method = "holm", pseudo_sens = TRUE,
                  prv_cut = 0.10, lib_cut = 1000, s0_perc = 0.05,
                  group = "SAR_type", struc_zero = TRUE, neg_lb = TRUE,
                  alpha = 0.05, n_cl = 2, verbose = TRUE,
                  global = TRUE, pairwise = TRUE, 
                  dunnet = TRUE, trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, 
                                      verbose = TRUE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = lme4::lmerControl(), 
                  mdfdr_control =  list(fwer_ctrl_method = "holm", B = 100), 
                  trend_control = list(contrast = list(matrix(c(1, 0, -1, 1),
                                                              nrow = 2, 
                                                              byrow = TRUE)),
                                       node = list(2),
                                       solver = "ECOS",
                                       B = 10))

res_table <- as.data.frame(output$res)
#write.csv(res_table, "ANCOMBC2_output_User.ID_SAR_group_Family_Taxa_Level_reference_control0.csv")

res_pair = as.data.frame(output$res_pair)
#write.csv(res_pair, "ANCOMBC2_res_pair_output_User.ID_SAR_group_Family_Taxa_Level_reference_control0.csv")

res_global = as.data.frame(output$res_global)
#write.csv(res_global, "ANCOMBC2_res_global_output_User.ID_SAR_group_Family_Taxa_Level_reference_control0.csv")

res_dunn = as.data.frame(output$res_dunn)
#write.csv(res_dunn, "ANCOMBC2_res_dunn_output_User.ID_SAR_group_Order_Taxa_Level_reference_control0.csv")
```

#Forams
##count data

```{r data}
forams <- read.csv("forams.csv", header=T)

forams_meta <- forams %>% 
  dplyr::select(ID, Site, OM_pct_10,porosity_10, DBD_10, chl_10, o2_min_cmems_10, o2_range_cmems_10,water_depth, TOC, LOI, SAR_2014,SAR_group,swm_d, sal_alt, curr_med, curr_range, lat, long, project, trawling)

forams_count <- forams %>%
   dplyr::select(-Site, -OM_pct_10,-porosity_10, -DBD_10, -chl_10, -o2_min_cmems_10, -o2_range_cmems_10, -water_depth, -TOC, -LOI, -SAR_2014,-SAR_group, -swm_d ,-sal_alt, -curr_med, -curr_range, -lat, -long, -project, -trawling, - OPD)%>%
  gather(spec,count, 2:ncol(.))%>%
          filter(count > 0)

forams_relab <- forams_count %>%
    group_by(ID) %>% 
    mutate(relab = count/sum(count)) %>%
    ungroup()

forams_dom <- forams_relab %>%
  filter(spec %in% c("Adercotryma.glomerata","Ammonia.falsobeccari", "Ammoscalaria.pseudospiralis","Bulimina.marginata","Cassidulina.laevigata","Eggeroloides.scaber","Elphidium.excavatum","Epistominella.vitrea","Hyalinea.balthica","Nonionella.labradorica","Nonionella.sp...juvenile.not.identified.","Nonionella.sp..T1","Nonionella.turgida","Stainforthia.fusiformis","Textularia.earlandi"))

forams.rare <- forams_relab %>% anti_join(forams_dom, by="spec")%>% mutate(spec="zz_Others_rare_<2%")

forams_tot <- rbind(forams_dom, forams.rare)

forams_combine_sum <- forams_tot %>% left_join(forams_meta, by="ID")

forams_combine <- forams_relab%>% left_join(forams_meta, by="ID")

```

```{r alpha diversity}
#alpha diversity
example_input_data <- forams_combine %>%
  dplyr::select(spec, ID, count)%>%
  spread(ID,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "spec")

Cmin <- min(colSums(example_input_data))
Cmin

SRS_output <- SRS(data = example_input_data, Cmin = as.integer(Cmin))

SRSshannon<- SRS_output %>%
  t()%>%
  data.frame()%>% 
  rownames_to_column(var="ID")%>% 
  plyr::ddply(~ID, function(x) {vegan::diversity(x[-1], index="shannon")}) %>%
  dplyr::rename(shannon= V1) %>% 
  left_join(forams_meta, by="ID")

shan.lm <- lm(shannon ~ SAR_2014, SRSshannon)


SRSshannon$SAR_type<- factor(SRSshannon$SAR_type,levels=c("MPA",
                    "low" ,
                   "medium",
                    "high",
                   "very high"))



alpha_div <-SRSshannon %>%
 ggplot(aes(x = SAR_2014, y = shannon, color=SAR_type, group=as.character(SAR_2014))) +
  geom_point(size=7) +
 geom_point(size=5) +
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
 labs(x = "SAR 2014", y = "Shannon´s H") +
  scale_color_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))+
   theme_classic()+  theme(
    legend.position = 'right',
    axis.text.x=element_text(angle = -45, hjust = 0)
  )+
    geom_vline(xintercept = 1.0,linetype = "solid")+
   geom_abline(slope = coef(shan.lm)[["SAR_2014"]], 
              intercept = coef(shan.lm)[["(Intercept)"]],
              linetype= "dashed", color="grey76")+
   guides(colour = guide_legend(override.aes = list(size=6), title="SAR 2014", nrow=13))+
   scale_x_continuous(breaks = scales::pretty_breaks(n = 7))+
 
  labs(title = paste("Adj R2 = ",signif(summary(shan.lm)$adj.r.squared, 5),
"Intercept =",signif(shan.lm$coef[[1]],5 ),
" Slope =",signif(shan.lm$coef[[2]], 5),
" P =",signif(summary(shan.lm)$coef[2,4],5)), size=6)




#Stats
test2 <-lme(shannon ~ 1 + as.numeric(SAR_2014), data=SRSshannon, random=~1|Site, method="REML") 
aov2 <-anova(test2)
aov2
```

```{r beta diversity db-RDA}
#dissimilarity matrix based on Bray Curtis
forams_wide_relab <- forams_combine %>%  dplyr::select(spec, ID, relab) %>% 
  spread(spec,relab, fill= 0) %>% 
  remove_rownames() %>%
  column_to_rownames(var = "ID")

BC.dist=vegdist(forams_wide_relab, distance="bray")

#use capscale to make a db-RDA
dbRDA=vegan::capscale(BC.dist ~
                curr_range+
                sal_alt,
              data=forams_meta, dist="bray")

#check for collinearity of your env.var.
vif<- vif.cca(dbRDA)
vif 

set.seed(10)
anova(dbRDA, by = "margin",model="direct", permutations = 9999)


##Calculate the eigenvalues for the first and second dimension
dpRDA.eigs    <- dbRDA$CCA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))
dpRDA.eigs.uncon    <- dbRDA$CA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))

#Overview how much will be epxlained by the axis
expl_var <- c(dpRDA.eigs , dpRDA.eigs.uncon) 




scrs <- vegan::scores(dbRDA, display=c("sp","wa","lc","bp","cn"))
df_sites<-data.frame(scrs$sites,t(as.data.frame(rownames(scrs$sites))))%>%
  dplyr::select(CAP1, CAP2)%>%
  rownames_to_column(var="ID")
df_sites <-df_sites

df_sites <- df_sites %>% 
  inner_join(forams_meta, by="ID")



df_sites$SAR_type<- factor(df_sites$SAR_type,levels=c("MPA",
                    "low" ,
                   "medium",
                    "high",
                   "very high"))

#Draw sites
p<-ggplot()
p<-p+geom_point(data=df_sites,aes(CAP1,CAP2,colour=SAR_type, size=6))+
  #scale_color_manual(values=cols.trawl)
  scale_color_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))
# scale_color_stepsn(n.breaks = 8, colours = rev(viridis::viridis(10)))
#Draw biplots
multiplier <- vegan:::ordiArrowMul(scrs$biplot*1)

df_arrows<- scrs$biplot*multiplier
colnames(df_arrows)<-c("CAP1","CAP2")
df_arrows=as.data.frame(df_arrows)

p<-p+geom_segment(data=as.data.frame(df_arrows), aes(x = 0, y = 0, xend = CAP1, yend = CAP2),
                 arrow = arrow(length = unit(0.2, "cm")))

p<-p+geom_text(data=as.data.frame(df_arrows*1),aes(CAP1, CAP2, label = rownames(df_arrows)), size=5)+
  theme_classic()+
  theme(legend.position = "right")+
    guides(colour = guide_legend(override.aes = list(size=6), title="SAR 2014", nrow=13))
p
```

```{r bubble plot}
forams_combine_sum$SAR_type<- factor(forams_combine_sum$SAR_type,levels=c("MPA",
                    "low" ,
                   "medium",
                    "high",
                   "very high"))


forams_combine_sum%>%
   group_by(SAR_type, spec)%>%
  mutate(relab=mean(relab))%>%
  ungroup()%>%
      mutate(spec = reorder(spec, -relab, sum)) %>% 
  ggplot(aes(x=SAR_type, y=spec, size=relab, fill=spec)) +
    geom_point( shape=21, color="black") +
    scale_size_area(max_size=20, name="Relative abundance ") +
    scale_fill_viridis(discrete=T, guide=FALSE, option="A") +
    theme_ipsum() +
    theme(legend.position="right") +
    ylab("spec") +
    xlab("SAR ")

```

```{r combine data}
first <-ggarrange(alpha_div, p, ncol=2, labels=c("A","B"))
ggarrange(first, all, nrow=2, labels=c("","C"))
```


#Microfauna
##16S data

```{r data}
meta <- read.csv("16S_Kattegat.csv", header=T)%>%
  dplyr::rename(ID=sampleID_for_now) %>% filter(project %in% "kattegat")
meta$User.ID <- gsub(".1b", "", meta$User.ID)  
meta$User.ID <- gsub(".2b", "", meta$User.ID)  


counts <- read.table("dada2/ASV_table.tsv", stringsAsFactors = F, header =T)%>%
          gather(sample,count, 2:ncol(.))%>%
          filter(count > 0)%>%
          dplyr::rename(ID = sample)

taxa <- read.delim("dada2/ASV_tax.sbdi-gtdb.tsv",stringsAsFactors = FALSE, header=TRUE)%>%
  replace_with_na(list(Domain=""))%>%
        replace_with_na(list(Kingdom=""))%>%
        replace_with_na(list(Phylum=""))%>%
        replace_with_na(list(Class=""))%>%
        replace_with_na(list(Order=""))%>%
        replace_with_na(list(Family=""))%>%
        replace_with_na(list(Genus=""))%>%
        replace_with_na(list(Species=""))%>%
        replace_na(list(Domain="zz_Unclassified"))%>%
        replace_na(list(Kingdom="zz_Unclassified"))%>%
        replace_na(list(Phylum="zz_Unclassified"))%>%
        replace_na(list(Class="zz_Unclassified"))%>%
        replace_na(list(Order="zz_Unclassified"))%>%
        replace_na(list(Family="zz_Unclassified"))%>%
        replace_na(list(Genus="zz_Unclassified"))%>%
        replace_na(list(Species="zz_Unclassified"))

#combine tables
Tab_all_n <- counts%>% 
  left_join(meta, by="ID") %>% 
  left_join(taxa, by="ASV_ID")%>%
  dplyr::select( -NGI.ID, -X..Q30, -cutadapt_total_processed, -cutadapt_passing_filters, -cutadapt_passing_filters_percent, -DADA2_input, -filtered, -denoisedF, -denoisedR, -merged, -nonchim, -input_tax_filter, -filtered_tax_filter, -lost, -retained_percent, -lost_percent, -depth, -Kreads, -replicate )%>%
  filter(project %in% "kattegat")

#relab
Tab_all <- Tab_all_n %>%
  group_by(ID) %>% 
  filter(sum(count) >= 1000) %>% 
  mutate(relab = count/sum(count)) %>%
  mutate(OM_pct = mean(OM_pct))%>%
  mutate(porosity = mean(porosity))%>%
  mutate(DBD = mean(DBD))%>%
  mutate(chl =mean(chl))%>%
  ungroup()%>%
  rename(name = User.ID)

#raw counts wide format
countsRAW <- Tab_all %>%  
  #group_by(User.ID) %>% 
  #filter(sum(count) >= 1000) %>% 
  #ungroup() %>%
  dplyr::select(ASV_ID, ID, count) %>% 
  spread(ASV_ID,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "ID")

wide_relab_cat <- Tab_all %>%  
  group_by(ASV_ID, User.ID)%>%
 summarise(relab=mean(relab))%>%
   ungroup()%>%
  dplyr::select(ASV_ID, User.ID, relab) %>% 
  spread(ASV_ID,relab, fill= 0) %>% 
  remove_rownames() %>%
  column_to_rownames(var = "User.ID")

#wide_relab_cat2 <- Tab_all %>% 
 # dplyr::select(ASV_ID, ID, relab) %>% 
 # spread(ID,relab, fill= 0) %>% 
  #remove_rownames() %>%
 # column_to_rownames(var = "ASV_ID")
```

```{r define colors}

cols.trawl <- c(
  "trawled" = "maroon",
  "control" = "yellowgreen"
)

cols.site <- c(
 "CL1" ="#95004b",
 "CL2" = "#c50046",
  "CL3" ="#ff9a94",
"CL4"  ="#500200",
"CL5"  ="#291200",
"CL8"  = "#8e4100",
"Anholt" = "#ffc197",
"N10" = "#ffa93b",
"N12" = "#fff1d0",
"PP1" ="#b99d00",
"PP2" ="#f6ff70",
"PP3" ="#adc000",
"PP4" ="#6bf63c",
"PP5" ="#0d4f00",
"PP6" ="#00bb50",
"PP7" ="#009762",
"PP10" ="#002d1d",
"PP11" ="#7dffcf",
"R3" ="#01f4f9",
"R5" ="#c8f6ff",
"SP3" ="#86d0ff",
"SP4" ="#0155a7",
"SP5" ="#283ae1",
"SP6" ="#f1cbff",
"SP7" ="#ff77ce",
"SP8" ="#ffc3d5"
)


cols.SAR <- c(
  "0"="grey7",
  "1.597"="#d2522c",
  "2.522"="#de946d",
  "2.768"="#9d5e2f",
  "4.209"="#d69332",
  "4.301"="#ada85c",
  "4.592"="#b3b736",
  "4.633"="#6a7227",
  "5.181"="#63b445",
  "5.24"="#3a814d",
  "5.675"="#5fbe84",
  "5.76"="#3fbfbc",
  "6.238"="#4f9ed5",
  "6.273"="#5d5fa5",
  "7.164"="#5e6bdb",
  "7.259"="#9a92dd",
  "8.595"="#a25bc7",
  "10.833"="#cc53b2",
  "12.478"="#db88b2",
  "13.483"="#9d4b6c",
  "14.375"="#d84380"
  )

cols.SAR_group <- c(
  "0" ="#e1c2aa",
"<3"="#bed8b5",
"<6" ="#a2d5d6",
"<9" ="#afc2e3",
"<15" ="#debbd4"
)

```

```{r rarefaction Supplemental}
#rarefy
countsRAW <- Tab_all_n  %>% 
  dplyr::select(ASV_ID, ID, count) %>% 
  spread(ASV_ID,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "ID")

(raremax <- min(rowSums(countsRAW))) #98265

#Rarefaction curve plot
out<- rarecurve(countsRAW, step = 20, sample = raremax, cex = 0.6, label = F)
Nmax <- sapply(out, function(x) max(attr(x, "Subsample")))
Smax <- sapply(out, max)
 
 
col <- c("black", "black")
set.seed(3)
grp <- factor(sample(seq_along(col), nrow(countsRAW), replace = TRUE))
cols <- col[grp] 
 
 
 plot(c(1, max(Nmax)), c(1, max(Smax)), xlab = "Sample Size",
     ylab = "Species", type = "n")
abline(v = raremax)
for (i in seq_along(out)) {
    N <- attr(out[[i]], "Subsample")
    lines(N, out[[i]], col = cols[i])
}
```

```{r alpha diversity}
#test along the SRS value instead of trawled-not trawled

#SRS analysis
example_input_data <- Tab_all %>%
  group_by(ASV_ID, User.ID)%>%
 summarise(count=sum(count))%>%
   ungroup()%>%
  dplyr::select(ASV_ID, User.ID, count)%>%
  spread(User.ID,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "ASV_ID")

#(e.g. species counts of the library with the lowest sequencing depth):
Cmin <- min(colSums(example_input_data))
Cmin

SRS_output <- SRS(data = example_input_data, Cmin = Cmin)

#Shannon Diversity Index
SRSshannon<- SRS_output %>%
  t()%>%
  data.frame()%>% 
  rownames_to_column(var="User.ID")%>% 
  plyr::ddply(~User.ID, function(x) {vegan::diversity(x[-1], index="shannon")}) %>%
  dplyr::rename(shannon= V1) %>% #Shannon 
  left_join(Tab_all, by="User.ID")



SRSshannon$SAR_type<- factor(SRSshannon$SAR_type,levels=c("MPA",
                    "low" ,
                   "medium",
                    "high",
                   "very high"))

shan.lm <- lm(shannon ~ SAR_2014_10, SRSshannon)

alpha_site_shan <-SRSshannon %>%
 ggplot(aes(x = SAR_2014_10, y = shannon, color=SAR_type, group=as.character(SAR_2014_10))) +
   geom_point(size=7) +
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
 labs(x = "SAR 2014", y = "Shannon´s H", size=6) +
    scale_color_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))+
   theme_classic()+  theme(
    legend.position = 'right',
    axis.text.x=element_text(angle = -45, hjust = 0)
  )+
    geom_vline(xintercept = 1.0,linetype = "solid")+
   geom_abline(slope = coef(shan.lm)[["SAR_2014_10"]], 
              intercept = coef(shan.lm)[["(Intercept)"]],
              linetype= "dashed", color="grey76")+
   guides(colour = guide_legend(override.aes = list(size=6), title="SAR 2014", nrow=13))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 7))+
 
  labs(title = paste("Adj R2 = ",signif(summary(shan.lm)$adj.r.squared, 5),
"Intercept =",signif(shan.lm$coef[[1]],5 ),
" Slope =",signif(shan.lm$coef[[2]], 5),
" P =",signif(summary(shan.lm)$coef[2,4],5)), size=6)

#Stats
#Shannon
SRSshannon_av <- SRSshannon%>%
  group_by(ID, SAR_2014_10,  site)%>%
  summarise(shannon = mean(shannon))%>%
  ungroup()

test2 <-lme(shannon ~ 1 + SAR_2014_10, data=SRSshannon_av, random=~1|site, method="REML") 
aov2 <-anova(test2)
aov2

```

```{r bubble plot}

Tab_all$SAR_type<- factor(Tab_all$SAR_type,levels=c("MPA",
                    "low" ,
                   "medium",
                    "high",
                   "very high"))


# Most basic bubble plot
micro_over <- Tab_all %>%
    group_by(SAR_type, Order)%>%
  filter(relab>0.005)%>%
  ungroup() %>%
  group_by(SAR_type, Order)%>%
  mutate(relab=mean(relab))%>%
  ungroup()%>%
      filter(!Order %in% "zz_Unclassified")
  
  
micro_under2 <-Tab_all %>%
    filter(!Order %in% "zz_Unclassified")%>%
    group_by(SAR_type, Order)%>%
  filter(!relab>0.005) %>%
  mutate(Order = "Other")

micro_all <-rbind(micro_over, micro_under2)
  
  
 micro_over%>%
      mutate(Order = reorder(Order, -relab, sum)) %>% 
  ggplot(aes(x=SAR_type, y=Order, size=relab, fill=Order)) +
    geom_point( shape=21, color="black") +
    scale_size(range = c(.1, 24), name="Relative abundance >0.5 %") +
    scale_fill_viridis(discrete=TRUE, guide=FALSE, option="A") +
    theme_ipsum() +
    theme(legend.position="right") +
    ylab("Order") +
    xlab("SAR 2014")

# ggsave(file="../../../Kattegat/manuscript/figures/pdf/bubble_fig_4_microrganisms.pdf", width=6, height=6, dpi=300)

```

```{r db-RDA }
wide_dbrda <-Tab_all%>%
  dplyr::select(ASV_ID, User.ID, count)%>%
  group_by(ASV_ID, User.ID)%>%
    filter(row_number() ==1)%>%
  ungroup()%>%
  group_by(User.ID)%>%
  mutate(count=sum(count))%>%
mutate(relab = count/sum(count)) %>%
ungroup()%>%
  dplyr::select(ASV_ID, User.ID, relab) %>% 
  spread(ASV_ID,relab, fill= 0) %>% 
  remove_rownames() %>%
  column_to_rownames(var = "User.ID")
#dissimilarity matrix based on Bray Curtis
BC.dist=vegdist(wide_dbrda, distance="bray")

meta_kat_sum <- meta%>%
  filter(project %in% "kattegat")%>%
  dplyr::select(User.ID, water_depth, OM_pct , porosity ,DBD , chl , BPc_WW_10 , IPc_WW_10 ,  totWW_10 ,BQI_2009_10 , D_10 , 
                 SAR_2014_10 , swm_d_10 ,  log_swm_d_plus_1_10,salt_range_cmems_10, o2_range_cmems_10,curr_median_cmems_10,o2_min_cmems_10, PRT.CHO_ratio_0.2cm,curr_range_cmems_10, SAR_group) %>%
  group_by(User.ID)%>%
  mutate(OM_pct = mean(OM_pct))%>%
  mutate(porosity =mean(porosity))%>%
  mutate(DBD =mean(DBD))%>%
  mutate(chl = mean(chl))%>%
  filter(row_number() ==1)%>%
  ungroup() 


  
  
#use capscale to make a db-RDA
dbRDA=capscale(BC.dist ~
                 SAR_2014_10 + 
               PRT.CHO_ratio_0.2cm +
                 salt_range_cmems_10+ 
               o2_min_cmems_10,
                  data=meta_kat_sum , dist="bray")

#check for collinearity of your env.var.
vif<- vif.cca(dbRDA)
vif 

set.seed(10)
anova(dbRDA, by = "margin",model="direct", permutations = 9999)

##Calculate the eigenvalues for the first and second dimension
dpRDA.eigs    <- dbRDA$CCA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))
dpRDA.eigs.uncon    <- dbRDA$CA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))

#Overview how much will be epxlained by the axis
expl_var <- c(dpRDA.eigs , dpRDA.eigs.uncon) 

#Plot
meta_kat <- meta %>%
  filter(project %in% "kattegat")


scrs <- vegan::scores(dbRDA, display=c("sp","wa","lc","bp","cn"))
df_sites<-data.frame(scrs$sites,t(as.data.frame(rownames(scrs$sites))))%>%
  dplyr::select(CAP1, CAP2)%>%
  rownames_to_column(var="User.ID")
df_sites <-df_sites

df_sites <- df_sites %>% 
  inner_join(meta_kat, by="User.ID")


df_sites$SAR_group<- factor(df_sites$SAR_group,levels=c("0", "<3" ,"<6","<9","<15"))


#Draw sites
p<-ggplot()
p<-p+geom_point(data=df_sites,aes(CAP1,CAP2,colour=SAR_group, size=5))+
      scale_color_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))
#Draw biplots
multiplier <- vegan:::ordiArrowMul(scrs$biplot*1)

df_arrows<- scrs$biplot*multiplier
colnames(df_arrows)<-c("CAP1","CAP2")
df_arrows=as.data.frame(df_arrows)

p<-p+geom_segment(data=as.data.frame(df_arrows), aes(x = 0, y = 0, xend = CAP1, yend = CAP2),
                 arrow = arrow(length = unit(0.2, "cm")))

p<-p+geom_text(data=as.data.frame(df_arrows*1),aes(CAP1, CAP2, label = rownames(df_arrows)))+
  theme_classic()+
  theme(legend.position = "right")
p

```

```{r combine figures}
ab <-ggarrange(alpha_site_shan, p, ncol=2, labels=c("A","B"))
ggarrange(ab, bar, nrow=2, labels=c("","C"))
```

```{r differential abundance analysis }

filter <- Tab_all %>%
    group_by(SAR_type, Order)%>%
  filter(relab>0.005)%>%
  ungroup() %>%
  group_by(SAR_type, Order)%>%
  mutate(relab=mean(relab))%>%
  ungroup() %>% dplyr::select(Order)%>%
  unique()

df <- Tab_all %>% 
  right_join(filter, by="Order")%>%
   group_by(ASV_ID, User.ID)%>%
 summarise(count=sum(count))%>%
   ungroup()%>%
 
  spread(User.ID,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "ASV_ID")

meta_da<- meta %>%
  filter(project %in% "kattegat")%>%
  dplyr::select(User.ID, SAR_type, site)%>%
  group_by(User.ID)%>%
  filter(row_number() ==1)%>%
  ungroup()%>%
  remove_rownames()%>%
  column_to_rownames(var="User.ID")
meta_da$SAR_type <- as.character(meta_da$SAR_type)


OTU=otu_table(df, taxa_are_rows = TRUE)
META = sample_data(meta_da)
TAXA <- taxa %>% 
  dplyr::select("ASV_ID","Domain","Kingdom","Phylum","Class","Order","Family","Genus","Species")%>% 
  remove_rownames()%>%
  column_to_rownames(var="ASV_ID")
TAXA = as.matrix(TAXA)
TAXA=tax_table(TAXA)
phyl_obj <- phyloseq(OTU, META, TAXA)

sample_data(phyl_obj)$SAR_type <- as.factor(sample_data(phyl_obj)$SAR_type)
sample_data(phyl_obj)$SAR_type<- relevel(sample_data(phyl_obj)$SAR_type, "MPA")

output = ancombc2(data = phyl_obj, assay_name = "counts", tax_level = "Order",
                  fix_formula = "SAR_type", rand_formula = NULL,
                  p_adj_method = "holm", pseudo_sens = TRUE,
                  prv_cut = 0.10, lib_cut = 1000, s0_perc = 0.05,
                  group = "SAR_type", struc_zero = TRUE, neg_lb = TRUE,
                  alpha = 0.05, n_cl = 2, verbose = TRUE,
                  global = TRUE, pairwise = TRUE, 
                  dunnet = TRUE, trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, 
                                      verbose = TRUE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = lme4::lmerControl(), 
                  mdfdr_control =  list(fwer_ctrl_method = "holm", B = 100), 
                  trend_control = list(contrast = list(matrix(c(1, 0, -1, 1),
                                                              nrow = 2, 
                                                              byrow = TRUE)),
                                       node = list(2),
                                       solver = "ECOS",
                                       B = 10))

res_table <- as.data.frame(output$res)
write.csv(res_table, "ANCOMBC2_output_User.ID_SAR_Type_Order_Taxa_Level_reference_controlMPA.csv")

res_pair = as.data.frame(output$res_pair)
write.csv(res_pair, "ANCOMBC2_res_pair_output_User.ID_SAR_Type_Order_Taxa_Level_reference_controlMPA.csv")

res_global = as.data.frame(output$res_global)
write.csv(res_global, "ANCOMBC2_res_global_output_User.ID_SAR_Type_Order_Taxa_Level_reference_controlMPA.csv")

res_dunn = as.data.frame(output$res_dunn)
write.csv(res_dunn, "ANCOMBC2_res_dunn_output_User.ID_Type_Order_Taxa_Level_reference_controlMPA.csv")
```


#Sediment chemistry
##Environmental data

```{r Env. Var.}


meta_kat_sum$SAR_type<- factor(meta_kat_sum$SAR_type,levels=c("MPA",
                    "low" ,
                   "medium",
                    "high",
                   "very high"))


org <-meta_kat_sum %>%
  ggplot(aes(x=SAR_2014_10, y=OM_pct, group=SAR_type, fill=SAR_type))+
      scale_fill_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))+
  geom_point(shape=21, size=7)+
  theme_classic()+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="right")+
  ylab("Organic matter (%)")+
  xlab("SAR 2014")+
guides(colour = guide_legend(override.aes = list(size=6), title="SAR 2014", nrow=13))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 7))


por <-meta_kat_sum %>%
  ggplot(aes(x=SAR_2014_10, y=porosity, group=SAR_type, fill=SAR_type))+
      scale_fill_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))+
  geom_point(shape=21, size=7)+
  theme_classic()+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="right")+
  ylab("Porosity (%)")+
  xlab("SAR 2014")+
guides(colour = guide_legend(override.aes = list(size=6), title="SAR 2014", nrow=13))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 7))


chl <-meta_kat_sum %>%
  ggplot(aes(x=SAR_2014_10, y=chl, group=SAR_type, fill=SAR_type))+
      scale_fill_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))+
  geom_point(shape=21, size=7)+
  theme_classic()+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="right")+
  ylab("Chlorophyll (µg/cm³)")+
  xlab("SAR 2014")+
guides(colour = guide_legend(override.aes = list(size=6), title="SAR 2014", nrow=13))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 7))


pro <-meta_kat_sum %>%
  ggplot(aes(x=SAR_2014_10, y=PRT.CHO_ratio_0.2cm, group=SAR_type, fill=SAR_type))+
      scale_fill_manual(values=c("#1a9f13","#b0a801","gold","#de6600","#FF3D00"))+
  geom_point(shape=21, size=7)+
  theme_classic()+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="right")+
  ylab("PRT/CHO")+
  xlab("SAR 2014")+
guides(colour = guide_legend(override.aes = list(size=6), title="SAR 2014", nrow=13))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 7))

dev.size()

ggarrange(org, por, chl, pro, ncol=2, nrow=2, labels=c("A","B","C","D"), common.legend = TRUE, legend = "right")


ggsave(file="../../../Kattegat/manuscript/figures/pdf/chemi_figure2.pdf", width=7, height=5.5, dpi=300)
```


```{r session info}

# Display current R session information
sessionInfo()
# Time of the most recent analysis
Sys.time()

```